name: potato_recognizer_mobile
description: Aplicación de reconocimiento de tipos de papas con TF Lite
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bloc: ^9.0.0
  camera: ^0.11.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_vision: ^1.1.4
  intl: ^0.20.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/app_logo.png"
  android: "app_logo"
  image_path_android: "assets/images/app_logo.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_logo.png"
