name: potato_recognizer_mobile
description: Aplicación de reconocimiento de tipos de papas con TF Lite
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.10.1

dependencies:
  bloc: ^8.1.4
  camera: ^0.11.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_vision: ^1.1.4
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

flutter_launcher_icons:
  android: true
  image_path_android: "assets/images/app-logo.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app-logo.png"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
