org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Configuraciones adicionales para mejorar el rendimiento de Gradle
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.caching=true

# Configuraciones para evitar problemas de memoria con Jetifier
android.jetifier.ignorelist=bcprov-jdk15on

# Configuración para soporte de páginas de 16KB
android.experimental.enableArtProfiles=true
